### ISSUE TITLE
Include CPPFLAGS to the build

### ISSUE THREAD

**Issue by andrade87** [twekkel/htpdate#22]
Hi twekkel,
thanks for your work!
Please, if possible include CPPFLAGS to the build.
I'm attached the .diff to the Makefile.
Thanks a lot
[Makefile.txt](https://github.com/twekkel/htpdate/files/9220213/Makefile.txt)

**Comment by angeloc** [comment]
@andrade87 
The software is in C, so CPPFLAGS are not needed at all. Moreover CFLAGS are passed to the Makefile when invoked.
This issue can be closed as is.

**Comment by twekkel** [comment]
CPPFLAGS were present in the Makefile in the past, but it actually didn't make any sense (as @angeloc stated correctly).

Closing.
