### ISSUE TITLE
Feed daemon updates into Chrony

### ISSUE THREAD

**Issue by hongkongkiwi** [twekkel/htpdate#26]
I love the idea of HTPDate, it's perfect for firewalled environments.

For devices which will be moving between firewalled and not, it would be great if htpdate could play nice with Chrony.

Using Chrony SOCK protocol we could feed updates to Chrony, so that HTPDate daemon could become another chrony timesource for if/when NTP is blocked or not available due to firewall.

Any chance this feature could be considered?

Chrony uses SOCK protocol to handle incoming updates (basically

**Comment by hongkongkiwi** [comment]
It sounds complicated, but I believe the format is pretty simple, Chrony creates the SOCK file, then you just have to check if the sock file exists and then send data in a specific format, here's an example from GPSD:
https://github.com/traveller42/gpsd/blob/774f18e9e27a5934fd0e3e514ea47de88ca9b5ba/timehint.c#L309

**Comment by twekkel** [comment]
I'm not considering this option. You can just run both daemons at the same time. Feel free to fork and implement!
