### ISSUE TITLE
Swapped month and day in Windows 11

### ISSUE THREAD

**Issue by sonvirgo** [twekkel/htpdate#29]
Today is 9th Feb 2023
So when I run htpdate, it swaps the date to 2nd Sept 2023
![Screenshot 2023-09-02 120254](https://user-images.githubusercontent.com/10823037/217722885-07455792-8d57-4c58-b7b1-9935cb8c3a24.png)
All my format setting is default to EN-US Windows 11
![Screenshot 2023-02-09 115431](https://user-images.githubusercontent.com/10823037/217722390-f998546a-8e39-4b26-91b9-469391c9a9e4.png)

**Comment by twekkel** [comment]
Wrong htpdate (this htpdate version doesn't even run on Winodws :)).

Try here https://github.com/bobwen-dev/htpdate
