### ISSUE TITLE
htpdate is not able to adjust the system time under significant drifting.

### ISSUE THREAD

**Issue by dzhou3** [twekkel/htpdate#41]
I am using htpdate v1.3.7 to sync my VM's system time with the command:

```/usr/sbin/htpdate -Fcdlst -p 2 -m 1800 -M 115200 https://my-time-server.com```

However, the VM's clock has a drifting rate of ~160 s/day (Drift 1943.98 PPM, 167.96 s/day). It looks like htpdate is not able to compensate the drift quickly enough to gradually catch up. Instead, the time diff becomes larger and larger. Is there a hard limit for the maximum allowed drifting rate?
I've also tried the flag -x. The kernel time parameter freq has been modified to the upper limit `32768000` but the problem still persists.

**Comment by twekkel** [comment]
It sounds not so much a htpdate limit, but a kernel adjustment limit.... I believe the maximum drift that can be corrected is something in the order of 500 PPM (I believe, not 100% sure... it is not something htpdate enforces).

You could try to minimize the drift by setting kernel frequency with 'adjtimex -f ..',. see if you can find a value that works... if adjtimex can not do it, htpdate (or ntp) can not do it either.

In general there should be another and better way to set a VM time, without htpdate (or ntp).

**Comment by dzhou3** [comment]
Thanks for the reply 🙇‍♂️.
With `adjtimex --print`, I've observed that the frequency reached the limit (frequency: 32768000 but tick is still 0) when htpdate was running in the slew mode (-x), but the time drift was still diverging. Then, I've tried pass the reported drift 1943.98 PPM to `scripts/adjtimex_parameters.sh` and ran the suggested command to tweak both frequency and tick, and it worked quite well. However, I don't see htpdate.c is trying to tweak `tick`. Is this deliberate for some reason?

**Comment by twekkel** [comment]
For usual drift values, you would never need to adjust tick... tick adjustments are only needed for "exceptional" cases.
"-x" would not work in your case... but now your initial htpdate command might just work out fine, crossing my fingers
